 [[redirects]]
  from = "/api/"
  to = "https://some-external-site.com/api/users/tickets/"
  to = "https://www.metaweather.com/api/"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}
