export const GET_WEATHER = "GET_WEATHER";
export const GET_CURRENT_WEATHER = "GET_CURRENT_WEATHER";
export const GET_SINGLE_WEATHER = "GET_SINGLE_WEATHER";
export const GET_WEATHER_QUERY_RESULT = "GET_WEATHER_QUERY_RESULT";
export const GET_WEATHER_BY_QUERY_RESULT = "GET_WEATHER_BY_QUERY_RESULT"
export const CLEAR_SEARCH_RESULT = "CLEAR_SEARCH_RESULT"
export const IS_LOADING = "IS_LOADING"
